# Generated by Django 5.2 on 2025-04-25 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('metodoDePagamento', models.CharField(blank=True, max_length=200, null=True)),
                ('precoImposto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precoFrete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precoFinal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('pagamentoConcluido', models.BooleanField(default=False)),
                ('pagoEm', models.DateTimeField(blank=True, null=True)),
                ('envioFeito', models.BooleanField(default=False)),
                ('enviadoEm', models.DateTimeField(blank=True, null=True)),
                ('criadoEm', models.DateTimeField(auto_now_add=True, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EnderecoDeEntrega',
            fields=[
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('cidade', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=200, null=True)),
                ('pais', models.CharField(blank=True, max_length=200, null=True)),
                ('precoFrete', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('imagem', models.ImageField(blank=True, default='/images/placeholder.png', null=True, upload_to='images/')),
                ('marca', models.CharField(blank=True, max_length=200, null=True)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('numAnalise', models.IntegerField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contagemEmEstoque', models.IntegerField(blank=True, default=0, null=True)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('qtd', models.IntegerField(blank=True, default=0, null=True)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('imagem', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.pedido')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Revisao',
            fields=[
                ('nome', models.CharField(blank=True, max_length=200, null=True)),
                ('avaliacao', models.IntegerField(blank=True, default=0, null=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('criadoEm', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.produto')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
